# Generated by Django 5.0.7 on 2024-08-03 20:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="hotel",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="room",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="user",
        ),
        migrations.DeleteModel(
            name="Hotel",
        ),
        migrations.DeleteModel(
            name="Room",
        ),
        migrations.DeleteModel(
            name="Reservation",
        ),
    ]
