# Generated by Django 5.0.7 on 2024-08-11 05:35

from django.db import migrations


def populate_demo_data(apps, schema_editor):
    Hotel = apps.get_model("reservations", "Hotel")
    Room = apps.get_model("reservations", "Room")
    User = apps.get_model("auth", "User")
    Reservation = apps.get_model("reservations", "Reservation")

    user1 = User.objects.create(username="user1", password="password1", is_active=True)
    user2 = User.objects.create(username="user2", password="password2", is_active=True)

    hotel1 = Hotel.objects.create(
        name="Hotel Sunshine",
        location="Sunnydale",
        description="A lovely hotel in Sunnydale.",
        admin=user1,
        is_active=True,
    )

    hotel2 = Hotel.objects.create(
        name="Hotel Moonlight",
        location="Moontown",
        description="A charming hotel in Moontown.",
        admin=user2,
        is_active=True,
    )

    Room.objects.create(
        hotel=hotel1, room_type="S", luxury="L", base_cost=100.00, available_rooms=10
    )
    Room.objects.create(
        hotel=hotel2, room_type="D", luxury="S", base_cost=150.00, available_rooms=5
    )

    Reservation.objects.create(
        user=user1,
        room=Room.objects.get(hotel=hotel1, room_type="S"),
        check_in_date="2024-08-01",
        number_of_days=3,
        total_cost=300.00,
    )

    Reservation.objects.create(
        user=user2,
        room=Room.objects.get(hotel=hotel2, room_type="D"),
        check_in_date="2024-08-05",
        number_of_days=2,
        total_cost=300.00,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0003_initial"),
    ]

    operations = [
        migrations.RunPython(populate_demo_data),
    ]
